stenope:
    providers:
        App\Model\Article: '%kernel.project_dir%/content/blog'
        App\Model\Certification: '%kernel.project_dir%/content/certif'
        App\Model\Job: '%kernel.project_dir%/content/job'
        App\Model\CaseStudy: '%kernel.project_dir%/content/case-study'
        App\Model\Member: '%kernel.project_dir%/content/member'
        App\Model\Technology: '%kernel.project_dir%/content/technologies'

    resolve_links:
        App\Model\Article: { route: 'blog_article', slug: 'article' }
        App\Model\CaseStudy: { route: 'case_study', slug: 'caseStudy' }
        App\Model\Technology: { route: 'technology', slug: 'technology' }
