name: Remove old artifacts

on:
  schedule:
    # Every day at 1am
    - cron: '0 1 * * *'

jobs:
  remove-old-artifacts:
    name: 'ðŸ§¹ Remove old artifacts'
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: 'Remove old artifacts'
        uses: c-hive/gha-remove-artifacts@v1
        with:
          age: '1 day' # Remove all artifacts older than 1 day
          skip-recent: 3 # But at least skip the last 3 ones
